# The Docker image that will be used to build your app
image: ubuntu:20.04
# Functions that should be executed before the build script is run
before_script:
  - hwclock --hctosys
pages:
  script:
    - apt update
    - DEBIAN_FRONTEND=noninteractive apt install -y doxygen git
    - git clone https://github.com/jothepro/doxygen-awesome-css.git -b v2.1.0
    - doxygen docs/Doxyfile
    - sed -i -- 's/docs\/FOOT/FOOT/g' docs_temp/html/index.html
    - mv docs_temp/html/ public/
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public

